export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIE_INFO = 'GET_MOVIE_INFO';
export const CLEAR_CURRENT_MOVIE = 'CLEAR_CURRENT_MOVIE';
export const CHANGE_PAGE = 'CHANGE_PAGE';
